---
- name: Add User
  become: true
  ansible.builtin.shell: |
    useradd --no-create-home node_exporter

- name: Extract node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /usr/local/bin/node_exporter
    remote_src: yes

- name: Configure a service
  copy:
    content: |
      [Unit]
      Description=Prometheus Node Exporter Service
      After=network.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/node-exporter.service
    force: false

- name: Enable Systemctl node-exporter
  ansible.builtin.systemd:
    daemon_reload: true
    state: started
    enabled: true
    name: node-exporter