---
- name: "Update all packages"
  become: true
  yum:
    update_cache: yes

- name: "Install epel"
  become: true
  # become_method: sudo
  shell: |
    amazon-linux-extras install epel -y

- name: "reinstall libuv"
  become: true
  # become_method: sudo
  shell: |
    yum remove libuv -y    
    yum install libuv --disableplugin=priorities -y