# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaultds: &defaults
  docker:
      - image: circleci/node:13.8.0

jobs:
  create_infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: Create stack 
          command: |
            echo ${AWS_ACCESS_KEY_ID}
            echo ${AWS_SECRET_ACCESS_KEY}
            echo ${AWS_DEFAULT_REGION}
            echo ${CIRCLE_WORKFLOW_ID:0:5}
            aws cloudformation deploy \
                --template-file ./devops/cloudfomation/main.yaml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - c0:23:08:b3:df:bb:ba:c7:32:35:86:ea:c3:ee:af:e0
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            yes | ansible-playbook -i ./ansible/inventory ./ansible/main.yml
workflows:
  say-hello-workflow:
    jobs:
    # - create_infra
    - configure_infrastructure
  