# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaultds: &defaults
  docker:
      - image: circleci/node:18.0.0

orbs:
  welcome: circleci/welcome-orb@0.4.1

commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - run: echo Hello << parameters.to >> !!!

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: |
          yarn install
          yarn build
  test:
    <<: *defaults
    steps:
      - checkout
      - run: |
          yarn install
          yarn test --watchAll
  anylitist:
    <<: *defaults
    steps:
      - checkout
      - run: |
          yarn install
          yarn build
      # - persist_to_workspace:
      #     root: /tmp
      #     paths:
      #       - "**/*"
  read_log_file:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/logs
      - run: echo $(ls /tmp)
      - run: echo $(ls /tmp/logs/)
      - run: echo $(ls /tmp/logs/logs)
      - run: cat /tmp/logs/logs/log.txt
      - run: cat "/tmp/log.txt"
      - run:
          name: Only show when onFail
          when: on_fail
          command: echo 'On Fail'
workflows:
  say-hello-workflow:
    jobs:
    - welcome/run
    - print_world
    - read_log_file:
        requires:
          - print_world
  