# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaultds: &defaults
  docker:
      - image: circleci/node:13.8.0

jobs:
  create_infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: Create stack 
          command: |
            echo ${AWS_ACCESS_KEY_ID}
            echo ${AWS_SECRET_ACCESS_KEY}
            echo ${AWS_DEFAULT_REGION}
            echo ${CIRCLE_WORKFLOW_ID:0:5}
            aws cloudformation deploy \
                --template-file ./devops/cloudfomation/main.yaml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run: |
        export ANSIBLE_HOST_KEY_CHECKING=False
      - add_ssh_keys:
          fingerprints:
            - 2e:5e:38:0c:1c:00:b2:59:95:b5:0c:42:d3:28:e1:fe
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i ./ansible/inventory ./ansible/main.yml
workflows:
  say-hello-workflow:
    jobs:
    # - create_infra
    - configure_infrastructure
  