global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - localhost:9090
  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - ec2-13-213-35-211.ap-southeast-1.compute.amazonaws.com:9100